name: BitrainClock
description: Clock face UI for FlutterClock contest
version: 1.1.0+1
homepage: https://github.com/kroppli/bitrainclock

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.7.4
  flutter_native_splash: ^0.1.9

flutter_native_splash:
  color: "161616"
  ios: false
  fill: true

flutter_icons:
  image_path: "bitrainclock-icon.png" 
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - bitrainclock-icon.png
    - bitrainclock-label.png